#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 element_rect
#' @importFrom ggplot2 geom_abline
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_blank
#' @importFrom ggplot2 geom_histogram
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_rect
#' @importFrom ggplot2 geom_segment
#' @importFrom ggplot2 geom_smooth
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 geom_tile
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggplot_build
#' @importFrom ggplot2 guide_legend
#' @importFrom ggplot2 guides
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_light
#' @importFrom ggplot2 unit
#' @importFrom ggplot2 alpha
#' @importFrom ggplot2 xlim
#' @importFrom ggplot2 ylim
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 element_text
#' @importFrom graphics hist
#' @importFrom grDevices dev.off
#' @importFrom grDevices pdf
#' @importFrom gtools mixedsort
#' @importFrom stats complete.cases
#' @importFrom stats dbinom
#' @importFrom stats density
#' @importFrom stats glm
#' @importFrom stats integrate
#' @importFrom stats median
#' @importFrom stats qbinom
#' @importFrom stats quantile
#' @importFrom stats setNames
#' @importFrom tibble is_tibble
#' @importFrom tibble as_tibble
#' @importFrom tibble tibble
#' @importFrom tidyr pivot_wider
#' @importFrom utils capture.output
#' @importFrom utils object.size
#' @importFrom dplyr filter
#' @importFrom dplyr mutate
#' @importFrom dplyr select
#' @importFrom dplyr pull
#' @importFrom dplyr case_when
#' @importFrom dplyr arrange
#' @importFrom dplyr desc
#' @importFrom dplyr row_number
#' @importFrom dplyr bind_rows
#' @importFrom dplyr ungroup
#' @importFrom dplyr bind_cols
#' @importFrom dplyr full_join
#' @importFrom dplyr left_join
#' @importFrom dplyr rowwise
#' @importFrom dplyr n
#' @importFrom dplyr right_join
#' @importFrom dplyr group_split
#' @importFrom dplyr distinct
#' @importFrom dplyr summarise
## usethis namespace: end
NULL
